### ISSUE TITLE
GitHub API deprecation notice

### ISSUE THREAD

**Issue by xieve** [pinpox/base16-universal-manager#36]
> Hi @xieve,
> 
> On July 19th, 2020 at 08:56 (UTC) your personal access token (base16-universal-manager) using Go-http-client/1.1 was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/99037070/contents/
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

I'm not sure if this is an error on your side or on a libraries? Anyway I thought I'd report it.

**Comment by pinpox** [comment]
Hm, good catch! I'm not sure yet, will look into it. 

If I understand correctly, for now it  still works and it's (just) an informational message.
Did you run into any problems apart from the warning?
