### ISSUE TITLE
Does not work for templates hosted somewhere else than github

### ISSUE THREAD

**Issue by leftshift** [pinpox/base16-universal-manager#43]
Because of hard coded `raw.githubusercontent.com` urls, the manager does not work for templates hosted somewhere else, like https://git.sr.ht/~knezi/base16-wofi.

**Comment by pinpox** [comment]
I guess this could be easily fixed. I don't have the time to implement this right now, but I'm willing to merge PR's if you want to give it a try!

**Comment by paul-ri** [comment]
Ah, turns out I had the same issue with Wofi and I created this PR:
https://github.com/pinpox/base16-universal-manager/pull/58

**Comment by pinpox** [comment]
Fixed by #58
