### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by jo1gi** [pinpox/base16-universal-manager#46]
I have added some elements to the wiki. Can you make a pull request?
https://github.com/jo1gi/base16-universal-manager.wiki.git

**Comment by pinpox** [comment]
Hi, @jo1gi I can't access the link, is it private?

**Comment by jo1gi** [comment]
@pinpox It's only a link to the git repo. Here is a link to the Github wiki:
https://github.com/jo1gi/base16-universal-manager/wiki
Sry for being unclear.

**Comment by pinpox** [comment]
merged.
