### ISSUE TITLE
Could you create a release

### ISSUE THREAD

**Issue by jo1gi** [pinpox/base16-universal-manager#51]
I'm currently trying to make a nix package for base16-universal-manager and it would be nice to have a version to match it to. It does not have to be a 1.0.0 release, but just a 0.1.0 or 0.0.1.

**Comment by pinpox** [comment]
Sure!

**Comment by pinpox** [comment]
https://github.com/pinpox/base16-universal-manager/releases/tag/v1.0

Let me know if you need anything else to package it in nixos and when it's done, thanks for packaging it!
