### ISSUE TITLE
Download without Github Token

### ISSUE THREAD

**Issue by combro2k** [pinpox/base16-universal-manager#54]
From https://github.com/pinpox/base16-universal-manager/blob/a7c9c4e0cb4c7cce7359cc2e69e59f619586ce5f/helpers.go#L29
I can't use this program without github tokens :-(

**Comment by combro2k** [comment]
see PR :-) https://github.com/pinpox/base16-universal-manager/pull/55

**Comment by pinpox** [comment]
@combro2k Thanks!
closed by #55
